//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
namespace KontakteDatenbankDB.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Mailaddress
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
       public string Mailaddress1 { get; set; }

        public virtual Person Person { get; set; }

        public static Mailaddress FromEntity(Mailaddress entity)
        {
            return new Mailaddress()
            {
                Id = entity.Id,
                PersonId = entity.PersonId,
                Mailaddress1 = entity.Mailaddress1
            };
        }

        public Mailaddress ToEntity()
        {
            return new Mailaddress()
            {
                Id = Id,
                PersonId = PersonId,
                Mailaddress1 = Mailaddress1
            };
        }
    }
}
