//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
namespace KontakteDatenbankDB.Entities
{
    using PhoneNumbers;
    using System;
    using System.Collections.Generic;

    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string PhoneNumber1 { get; set; }

        public virtual Person Person { get; set; }

        public static object FromEntity(PhoneNumber x)
        {
            return x.Person;
        }

        public static object FromEntity(KontakteDatenbankDB.Models.PhoneNumbers phoneNumber)
        {
            return PhoneNumber.FromEntity(phoneNumber);
        }

        public static PhoneNumber ToEntity(Models.PhoneNumbers model)
        {
            PhoneNumber entity = new PhoneNumber
            {
                PhoneNumber1 = model.PhoneNumber
            };

            return entity;
        }
    }
}
