//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontakteDatenbankDB
{
    using PhoneNumbers;
    using System;
    using System.Collections.Generic;


    public class Models
    {
        public class PhoneNumbers
        {
            public string PhoneNumber { get; internal set; }
        }
    }
}